apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-python-app
  template:
    metadata:
      labels:
        app: simple-python-app
    spec:
      containers:
      - name: simple-python-app
        image: qwerty703/simple-python-app:latest
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: secret